Implemented site navbar and mobile menu
simian-ci/simian-ci.github.io pull request #29
Opened 2017-04-06 20:37 UTC by TheMightyPenguin

# Context

This was done by:

- Added markup and styling for navbar and alt-navbar
- Added markup and styling for mobile menu
- Added JS functions to handle navbar functionality
- Added JS functions to handle mobile menu functionality

Also refactor footer, no longer handled with flexbox so compatibility is increased.

## Links

- [Slack reference page](https://slack.com/enterprise)
- [Zeplin desktop design](https://app.zeplin.io/project.html#pid=586eaacfec55da7c2d67a2df&sid=58d442a75c718fae5988b30c)
- [Zeplin mobile design](https://app.zeplin.io/project.html#pid=586eaacfec55da7c2d67a2df&sid=587ac68562ad85054dcfaa4d&ref=slack)
- [Zeplin tablet design](https://app.zeplin.io/project.html#pid=586eaacfec55da7c2d67a2df&sid=58dd76421f2e8155af30c62e)

## Media

![Navbar Desktop](https://cloud.githubusercontent.com/assets/11748696/24774475/094ee1ea-1ae7-11e7-9ec6-4ceecdcaa30d.gif)
![Navbar Mobile](https://cloud.githubusercontent.com/assets/11748696/24774476/0956ad30-1ae7-11e7-8da6-040b47d53c61.gif)

2017-04-06 21:37 UTC, duranmla requested changes
There are some minor stuff to clarify before merge this

2017-04-06 21:37 UTC, duranmla commented on _sass/_components--navbar.scss
> +$transition--navbar-show:                           all 420ms cubic-bezier(.165,.84,.44,1);
always space after `,`

2017-04-06 21:37 UTC, duranmla commented on _sass/_layouts--global.scss
> +.no-scroll {
We can remove this class  and use bootstrap's one

2017-04-06 21:37 UTC, duranmla commented on _sass/_objects--buttons.scss
> +  // TODO: Check if this is correct with design (Ask mari)
I think so far you should know, and if it is a matter of asking let's wait for the answer before merge

2017-04-06 21:37 UTC, duranmla commented on _sass/_objects--menu-toggle.scss
> +  height: ($size--toggle-height*3) + ($size--toggle-offset*2);
separate operators like `$bla * 10`

2017-04-06 21:37 UTC, duranmla commented on _sass/_objects--menu-toggle.scss
> +    @include menu-toggle-boilerplate($size--toggle-height, $size--toggle-width, $color--toggle-background, $transition--toggle);
why so many of this?

2017-04-06 21:39 UTC, TheMightyPenguin commented on _sass/_objects--menu-toggle.scss
> +    @include menu-toggle-boilerplate($size--toggle-height, $size--toggle-width, $color--toggle-background, $transition--toggle);
That mixins adds the style necessary for displaying each line of the menu toggler! So its needed on the element itself and the pseudoelements

2017-04-07 13:28 UTC, duranmla approved these changes

2017-04-07 13:35 UTC, merged